# Linguagem e versão
[project]
name = "clarIA-api"
version = "0.1.0"


[build]
runtime = "python@3.10"
requirements = "requirements.txt"
env.PIP_ONLY_BINARY = ":all:"

# Pasta do app
[paths]
root = "."

# Como iniciar o serviço
[run]
# Comando para iniciar FastAPI via uvicorn
command = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

# Porta que o serviço expõe
[expose]
port = 8000
protocol = "http"
